- name: create gunicorn log file
  file:
    path: /var/opt/wsgi/black-goat/logs/gunicorn_supervisor.log
    state: touch
    mode: "u=rw,g=rw,o=r"
    owner: black-goat
    group: webapps
  become: yes
- name: copy gunicorn start script
  copy:
    src: files/gunicorn_start
    dest: /var/opt/wsgi/black-goat/bin/gunicorn_start
    mode: "u=rwx,g=rx,o=rx"
    owner: black-goat
    group: webapps
  become: yes
- name: copy celery start script
  copy:
    src: files/celery_start
    dest: /var/opt/wsgi/black-goat/bin/celery_start
    mode: "u=rwx,g=rx,o=rx"
    owner: black-goat
    group: webapps
  become: yes
- name: copy supervisord configuration for goat
  copy:
    src: files/supervisord__goat.conf
    dest: /etc/supervisord.d/goat.conf
    mode: "u=rw,g=r,o=r"
  become: yes
- name: reread supervisor configuration
  command: supervisorctl reread
  become: yes
- name: update supervisor with new configuration
  command: supervisorctl update
  become: yes
- name: restart black-goat gunicorn process
  command: supervisorctl restart black-goat
  become: yes
- name: restart black-goat celery process
  command: supervisorctl restart black-goat-celery
  become: yes
