- name: create app virtualenv with Python2.7.11
  command: virtualenv --python=/opt/bin/python2.7 /var/opt/wsgi/black-goat/env
  args:
    creates: /var/opt/wsgi/black-goat/env
  become: yes
  become_user: black-goat
- name: install python dependencies for app
  pip:
    requirements: /var/opt/wsgi/black-goat/black-goat/requirements.txt
    virtualenv: /var/opt/wsgi/black-goat/env
  become: yes
  become_user: black-goat
- name: make sure that gunicorn is installed in the app virtualenv
  pip:
    name: gunicorn
    virtualenv: /var/opt/wsgi/black-goat/env
  become: yes
  become_user: black-goat
